### ISSUE TITLE
Error when I use cron (ubuntu linux)

### ISSUE THREAD

**Issue by savoia-dev** [liamtill/wrfplot#1]
**Hello,
thanks for your great work. 
When I execute wrfplot.py in the bash shell I receive this error however when I run the script on the desktop everything works. I want to save the image on _png_ format
_What is the problem?_
_Thanks_**

> Reading in file:  /home/desktop/wrf/OUTPUT/2017-01-05_00_00_00/wrfout_d01_2017-01-05_00:00:00
Using map projection:  Lambert Conformal
Plotting Surface Chart for time:  2017-01-05 00:00:00
Traceback (most recent call last):
  File "wrfplot.py", line 946, in <module>
    surface()
  File "wrfplot.py", line 468, in surface
    plt.figure(figsize=(8,8))
  File "/usr/lib/pymodules/python2.7/matplotlib/pyplot.py", line 423, in figure
    **kwargs)
  File "/usr/lib/pymodules/python2.7/matplotlib/backends/backend_tkagg.py", line 79, in new_figure_manager
    return new_figure_manager_given_figure(num, figure)
  File "/usr/lib/pymodules/python2.7/matplotlib/backends/backend_tkagg.py", line 87, in new_figure_manager_given_figure
    window = Tk.Tk()
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1767, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

>

**Comment by liamtill** [comment]
Hi,

For making a plot, when invoking using a cron script, no back end GUI will be available therefore if you notice on line 22 in the file wrfplot.py ;

#matplotlib.use('Agg') # UNCOMMENT THIS ONLY WHEN INVOKING FROM CRON SCRIPT 

If you uncomment this, it will set the GUI back end to Agg, i believe this should solve your problems. 

Instead of Python trying to use its default back end Tkinter. 

If not please provide further details on;
When you say in the bash shell, do you mean a terminal you have opened on the desktop or have you SSH'd into the system. 

Are you issuing the --save command to create a PNG? 

Thanks
Liam

**Comment by liamtill** [comment]
Assuming this is now fixed therefore closing the issue.
